branch-defaults:
  master:
    environment: rails-beanstalk-env
    group_suffix: null
global:
  application_name: Canvas 2
  branch: null
  default_ec2_keyname: null
  default_platform: Ruby 2.2 (Puma)
  default_region: eu-central-1
  profile: eb-cli
  repository: null
  sc: git
