branch-defaults:
  master:
    environment: LowCost-env
    group_suffix: null
  rails-5-webpack-version:
    environment: Canvas51
    group_suffix: null
environment-defaults:
  Canvas51:
    branch: null
    repository: null
global:
  application_name: Canvas 2
  branch: null
  default_ec2_keyname: canvas51
  default_platform: Ruby 2.3 (Passenger Standalone)
  default_region: eu-central-1
  profile: eb-cli
  repository: null
  sc: git
