AWS_ACCESS_KEY_ID: AKIAJIQO3H4J54CHZW5A
AWS_SECRET_ACCESS_KEY: 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
AWS_REGION: eu-central-1
SENDMAIL_PASSWORD: 4607020a
SENDMAIL_USERNAME: billrozy@gmail.com
MAIL_HOST: localhost:3000